# Generated by Django 5.2.15 on 2026-06-26 19:23

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('section', models.CharField(max_length=20)),
                ('source_url', models.URLField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'section'), name='uq_edition_date_section')],
            },
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('agency', models.CharField(blank=True, default='', max_length=300)),
                ('raw_text', models.TextField()),
                ('search_text', models.TextField()),
                ('source_anchor', models.CharField(blank=True, default='', max_length=500)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='gazette.edition')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='gazette_act_search__f896b7_gin')],
                'constraints': [models.UniqueConstraint(fields=('edition', 'identifier'), name='uq_act_edition_identifier')],
            },
        ),
    ]
