# Generated by Django 5.2.15 on 2026-06-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='agency',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='act',
            name='source_anchor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='act',
            name='title',
            field=models.TextField(),
        ),
    ]
