# Generated by Django 5.2.15 on 2026-08-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0005_drop_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='text_pruned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
