# Generated by Django 5.2.15 on 2026-06-26 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gazette', '0001_initial'),
        ('watches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet', models.TextField(blank=True, default='')),
                ('rank', models.FloatField(default=0.0)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('state', models.CharField(default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='gazette.act')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='watches.watch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('watch', 'act'), name='uq_match_watch_act')],
            },
        ),
    ]
