# Generated by Django 5.2.15 on 2026-07-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='rank',
            field=models.FloatField(default=0.0, help_text='Advisory only: used to order results, not a guarantee of relevance.'),
        ),
    ]
