# Generated by Django 5.2.17 on 2026-08-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_alter_match_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matched_terms',
            field=models.JSONField(default=list),
        ),
    ]
