# Generated by Django 5.2.17 on 2026-08-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_match_matched_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='has_amount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='has_deadline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='names_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='signal_score',
            field=models.SmallIntegerField(db_index=True, default=0, help_text='Sum of the three signal flags, 0-3. What the feed and the digest order on.'),
        ),
    ]
