# Generated by Django 5.2.17 on 2026-08-29 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_match_signals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='confidence',
        ),
    ]
