# Generated by Django 5.2.15 on 2026-07-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0002_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='match_mode',
            field=models.CharField(choices=[('all', 'All terms must appear'), ('any', 'Any term may appear')], default='all', max_length=3),
        ),
    ]
