# Generated by Django 5.2.15 on 2026-06-26 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('watches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('body', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digests', to='watches.client')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('client', 'date'), name='uq_digest_client_date')],
            },
        ),
    ]
