# Generated by Django 5.2.15 on 2026-08-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digest',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digest',
            name='send_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='digest',
            name='send_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
