# Generated by Django 5.2.15 on 2026-06-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(default='running', max_length=20)),
                ('editions', models.IntegerField(default=0)),
                ('acts', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('enriched', models.IntegerField(default=0)),
                ('digests', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
