# Generated by Django 5.2.15 on 2026-08-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_runlog_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='runlog',
            name='digests_sent',
            field=models.IntegerField(default=0),
        ),
    ]
