# Generated by Django 5.2.17 on 2026-08-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_runlog_digests_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='runlog',
            name='created_enriched',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runlog',
            name='created_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runlog',
            name='ingested_acts',
            field=models.IntegerField(default=0),
        ),
    ]
